FROM node:16.15-alpine
# ENV APP_ROOT /home/app

WORKDIR /src

# COPY ./package.json $APP_ROOT
# COPY ./yarn.lock $APP_ROOT
# RUN yarn install
# COPY . $APP_ROOT

# COPY ./package.json ./package-lock.json ./
# RUN npm install

# EXPOSE 80
# CMD ["yarn", "dev"]
# CMD ["npm", "run", "start"]